routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('home');
})->middleware('auth');

Route::get('/gallery', 'AvatarController@index')->name('profile')->middleware('auth');
Route::resource('avatar', 'AvatarController')->middleware('auth');
Route::get('images/delete/{id}', 'GalleryController@deleteImage')->name('delete.image')->middleware('auth');
Route::get('delete_all', 'AvatarController@delAll')->name('deleteAll')->middleware('auth');
Route::post('/import_pdf','ProductController@export_pdf')->name('exportPDF')->middleware('auth');
Route::get('display', [
    'uses' => 'GalleryController@display'
])->middleware('auth');
Auth::routes();

/*Route::get('/pdf','ProductController@export_pdf')->name('export_pdf');*/
//Route::get('/pdf_final','ProductController@export_pdf')->name('export.pdf');

/*Route::post('/import','ProductController@import_excel');*/


/*Route::get('importExport', 'ProductController@importExport');
Route::get('downloadExcel/{type}', 'ProductController@downloadExcel');
Route::post('importExcel', 'ProductController@importExcel');*/




Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $table = 'products';
    protected $fillable = [
        'kodikos', 'eidos', 'temaxia', 'ekptosi','xondriki_timi','posotita'
    ];
}

app/User.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements HasMedia
{
    use Notifiable, HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function registerMediaCollections()
    {
        $this->addMediaCollection('avatar');
        /*->registerMediaConversions(function (Media $media) {
            $this->addMediaConversion('thumb')
            ->width(320)
            ->height(280);
        });*/
    }
}

app/Http/Controllers/AvatarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Avatar;

class AvatarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $avatar = User::find(3);
        $avatars = $avatar->getMedia('avatar');
        return view('gallery', compact('avatars'));
    }

    public function delAll() {
        auth()->user()->ClearMediaCollection('avatar');
        return redirect()->back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = auth()->user();
        if ($request->avatar) {
            foreach($request->avatar as $avatar) {
                $user->addMedia($avatar)->toMediaCollection('avatar');
            }
        }
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App;
use Illuminate\Support\Facades\Input;
use Form;

class GalleryController extends Controller
{
    public function deleteImage($avatar) {
        $avatars = auth()->user()->getMedia('avatar');
        $avatars[$avatar]->delete();
        return redirect()->back();
    }

    public function display() {
        $data = Input::get('agree');
        if ($data) {
            $avatar = User::find(3);
            $avatars = $avatar->getMedia('avatar');
            $temp = array();
            foreach ($data as $big_name){
                array_push($temp, $avatars->where('id', $big_name)->first());
            }
            $avatars = $temp;
            $pdf = PDF::loadView('pdf',compact('avatars'))->setPaper('a4', 'landscape');
            return $pdf->stream('labels.pdf');
        } else {
            return redirect()->back();
        }
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use PDF;
use Excel;
use App\Imports\ProductsImport;
use App\Item;
use DB;
use Illuminate\Support\Facades\Input;

class ProductController extends Controller
{
    public function export_pdf()
    {        
        $array1 = '';
        $array2 = '';
        $array3 = '';
        
        if (request()->file('file1') && request()->input('parafarmaka')) {
            $array1 = Excel::toArray(new ProductsImport, request()->file('file1'));
        } 
        if (request()->file('file2') && request()->input('otc')) {
            $array2 = Excel::toArray(new ProductsImport, request()->file('file2'));
        } 
        if (request()->file('file3') && request()->input('farmaka')) {
            $array3 = Excel::toArray(new ProductsImport, request()->file('file3'));
        }
        
        $input = Input::only('cover_date','extra_page','title1','subtitle1','title2','subtitle2','title3','subtitle3','editor1','editor2','editor3','quantity1','quantity2','quantity3');

        return view('pdf', compact('array1','array2','array3','input'));
    }
}

resources/views/gallery.blade.php
@extends('layouts.app')

@section('content')
@if (Auth::check())
<div class="container">
	<div class="row">
		<form action="{{route('avatar.store')}}" method="post" enctype="multipart/form-data">
			@csrf

			<div class="input-group mb-3">
				<div class="custom-file">
					<input type="file" name="avatar[]" class="custom-file-input" id="inputGroupFile01" multiple>
					<label class="custom-file-label" for="inputGroupFile01">Choose file</label>

				</div>
				<input type="submit" value="Upload" class="btn btn-success ml-4">
			</div>
		</form>
		<p id="demo"></p>
	</div>
</div>
@endif

{!! Form::open(array('action' => 'GalleryController@display','method' => 'GET'))!!}
@csrf
<div class="container-fluid">
	<div class="row">
		@foreach($avatars as $key => $avatar)
		<div class="card mr-2 mb-2" style="width: 300px!important; padding:5px;">
			<div class="form-group mb-3">
				<input type="checkbox" name="agree[]" id="myCheckbox{{$key}}" value="{{$avatar->id}}" />
				@if (Auth::check())
				<a href="{{route('delete.image', $loop->index)}}">&#10005;</a>
				@endif
				<label for="myCheckbox{{$key}}"><img class="card-img-top" src="{{$avatar->getFullUrl()}}" alt="Customer Logo">{{$avatar->file_name}}</label>
			</div>
		</div>
		@endforeach
	</div>
</div>
<div class="container-fluid mt-4">
	<div class="row">
		@if (Auth::check())
		<a class="btn btn-danger mr-3" href="{{route('deleteAll')}}">Delete All</a><br>
		@endif
	</div>
</div>
{!! Form::close() !!}

@endsection
<style>
	form { display: flex; flex-wrap: wrap; }
	.form-group a { float: right; color: red; font-size: 20px}
	.form-group img { cursor: pointer; }
	.row {margin-right: 30px!important; margin-left: 30px!important;}
</style>
<script>
function toggle(source) {
  checkboxes = document.getElementsByName('agree[]');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
}
</script> 

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid" style="max-width: 1600px; margin: 50px auto 50px auto; position: static;">
    <form action="{{ route('exportPDF') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="d-flex">
            <label style="width: 49%;">
                <div class="card-header d-flex justify-content-between align-items-center">
                    Ημερομηνία Εξωφύλλου
                    <input style="width: 60%; height: 35px; padding: 0 15px; border: 1px solid #ddd;" type="text" name="cover_date" id="cover_date" value="ΣΕΠΤΕΜΒΡΙΟΥ - ΟΚΤΩΒΡΙΟΥ 2019">
                </div>
            </label>
            <label style="width: 49%; margin-left: 20px;">
                <div class="card-header d-flex justify-content-between align-items-center" style="padding-bottom: 16px; padding-top: 20px;">
                    Έξτρα σελίδα οπισθόφυλλου
                    <input type="checkbox" name="extra_page" value="extra_page" checked="checked">
                </div>
            </label>
        </div>
        <div class="row">
            <div class="card col-sm-4 bg-light m-0 mt-3">
                <label>
                    <div class="card-header d-flex justify-content-between align-items-center">
                        Παραφάρμακα
                        <input type="checkbox" name="parafarmaka" value="parafarmaka" checked="checked">
                    </div>
                </label>
                <div class="card-body">
                    <label for="title1">Τίτλος</label>
                    <input style="width: 100%; height: 35px; padding: 0 15px; margin-bottom: 15px; border: 1px solid #ddd;" type="text" name="title1" id="title1" value="ΚΑΤΑΛΟΓΟΣ ΠΩΛΗΤΗ ΠΑΡΑΦΑΡΜΑΚΟΥ">
                    <label for="subtitle1">Υπότιτλος</label>
                    <input style="width: 100%; height: 35px; padding: 0 15px; margin-bottom: 15px; border: 1px solid #ddd;"type="text" name="subtitle1" id="subtitle1" value="ΣΕΠΤΕΜΒΡΙΟΥ - ΟΚΤΩΒΡΙΟΥ 2019">  
                    <textarea name="editor1" id="editor1" rows="10" cols="80">
                        <div style="text-align: center;">
                            <h3><strong><ins>ΠΕΡΙΕΧΟΜΕΝΑ</ins></strong></h3>
                            <br><br>
                            <h3><strong><ins>ΣΗΜΕΙΩΣΗ</ins></strong></h3><br>
                            <h3><strong>ΠΑΡΑΚΑΛΩ ΔΙΑΒΑΣΤΕ ΠΡΟΣΕΚΤΙΚΑ</strong></h3><br>
                        </div>
                        <b>Για την παρούσα προσφορά ισχύουν οι παρακάτω όροι:</b>
                        <br><br>
                        <ol>
                            <li>Το τεύχος αυτό συμπληρώνεται από εσάς και αποστέλλεται μέσω του δικτύου διανομής της αποθήκης πίσω σε μας ώστε να εκτελεστεί.</li>
                            <li>Η προσφορά εκτελείται και εξοφλείται ξεχωριστά από τις καθημερινές σας παραγγελίες.</li>
                            <li>Θα ενημερώνεστε πριν την αποστολή της προσφοράς σε εσάς για το συνολικό ποσό που αυτή ανέρχεται.</li>
                            <li>Η πληρωμή θα γίνεται με την παραλαβή της παραγγελίας.</li>
                            <li>Ελάχιστο ποσό παραγγελίας είναι τα 1000 €.</li>
                            <li>Δεν συσχετίζεται με τις υπόλοιπες προσφορές της φαρμακαποθήκης.</li>
                            <li>Μπορείτε να παραγγείλετε οποιεσδήποτε ποσότητες επιθυμείτε από κάθε προϊόν. Συμπληρώνετε την ποσότητα που επιθυμείτε στο κουτάκι δίπλα σε κάθε προϊόν.</li>
                            <li>Οι προσφορές ισχύουν κατόπιν ύπαρξης αποθέματος. Αν κάποιο από τα προϊόντα που παραγγείλατε έχει εξαντληθεί προσωρινά, θα ενημερώνεστε τηλεφωνικά από την αποθήκη μας ώστε να εξυπηρετηθείτε με τον καλύτερο δυνατό τρόπο.</li>
                            <li>Οι εκπτώσεις ακολουθούν την παρακάτω κλίμακα βάσει του
                                ΤΡΟΠΟΥ ΠΛΗΡΩΜΗΣ που εσείς θα επιλέξετε, ανεξάρτητα του ποσού που θα ανέρχεται η παραγγελία σας:
                                <ol>
                                    <li>Αν επιλέξετε να εξοφλήσετε το ποσό της προσφοράς τοις μετρητοίς,
                                    έχετε έκπτωση 5% επί του τιμολογίου της προσφοράς</li>
                                    <li>Αν επιλέξετε να εξοφλήσετε το ποσό της προσφοράς με
                                    επιταγή 60 ημερών, έχετε έκπτωση 4% επί του τιμολογίου της προσφοράς</li>
                                </ol>
                            </li>
                        </ol>
                    </textarea>              


                    <label style="margin-top:10px;">Αρχείο Excel</label>
                    <input style="border: unset; padding:0; outline: 1px solid #ccd4da;" type="file" name="file1" class="form-control"><br>
                    <label style="width: 100%;">
                        <div class="card-header d-flex justify-content-between align-items-center" style="padding-bottom: 16px; padding-top: 20px;">
                            Εμφάνιση Ποσοτήτων
                            <input type="checkbox" name="quantity1" value="quantity1">
                        </div>
                    </label>
                </div>
            </div>
            <div class="card col-sm-4 bg-light m-0 mt-3">
                <label>
                    <div class="card-header d-flex justify-content-between align-items-center">
                        OTC
                        <input type="checkbox" name="otc" value="otc" checked="checked">
                    </div>
                </label>
                <div class="card-body">
                    <label for="title2">Τίτλος</label>
                    <input style="width: 100%; height: 35px; padding: 0 15px; margin-bottom: 15px; border: 1px solid #ddd;" type="text" name="title2" id="title2" value="ΠΡΟΣΦΟΡΑ ΜΗΣΥΦΑ (OTC)">
                    <label for="subtitle2">Υπότιτλος</label>
                    <input style="width: 100%; height: 35px; padding: 0 15px; margin-bottom: 15px; border: 1px solid #ddd;" type="text" name="subtitle2" id="subtitle2" value="ΣΕΠΤΕΜΒΡΙΟΥ - ΟΚΤΩΒΡΙΟΥ 2019">                
                    <textarea name="editor2" id="editor2" rows="10" cols="80">
                        <div style="text-align: center;">
                            <h3><strong><ins>ΠΕΡΙΕΧΟΜΕΝΑ</ins></strong></h3>
                            <br><br>
                            <h3><strong><ins>ΣΗΜΕΙΩΣΗ</ins></strong></h3><br>
                            <h3><strong>ΠΑΡΑΚΑΛΩ ΔΙΑΒΑΣΤΕ ΠΡΟΣΕΚΤΙΚΑ</strong></h3><br>
                        </div>
                        <b>Για την παρούσα προσφορά ισχύουν οι παρακάτω όροι:</b>
                        <br><br>
                        <ol>
                            <li>Το τεύχος αυτό συμπληρώνεται από εσάς και αποστέλλεται μέσω του δικτύου διανομής της αποθήκης πίσω σε μας ώστε να εκτελεστεί.</li>
                            <li>Η προσφορά εκτελείται και εξοφλείται ξεχωριστά από τις καθημερινές σας παραγγελίες.</li>
                            <li>Θα ενημερώνεστε πριν την αποστολή της προσφοράς σε εσάς για το συνολικό ποσό που αυτή ανέρχεται.</li>
                            <li>Η πληρωμή θα γίνεται με την παραλαβή της παραγγελίας.</li>
                            <li>Ελάχιστο ποσό παραγγελίας είναι τα 1000 €.</li>
                            <li>Δεν συσχετίζεται με τις υπόλοιπες προσφορές της φαρμακαποθήκης.</li>
                            <li>Μπορείτε να παραγγείλετε οποιεσδήποτε ποσότητες επιθυμείτε από κάθε προϊόν. Συμπληρώνετε την ποσότητα που επιθυμείτε στο κουτάκι δίπλα σε κάθε προϊόν.</li>
                            <li>Οι προσφορές ισχύουν κατόπιν ύπαρξης αποθέματος. Αν κάποιο από τα προϊόντα που παραγγείλατε έχει εξαντληθεί προσωρινά, θα ενημερώνεστε τηλεφωνικά από την αποθήκη μας ώστε να εξυπηρετηθείτε με τον καλύτερο δυνατό τρόπο.</li>
                            <li>Οι εκπτώσεις ακολουθούν την παρακάτω κλίμακα βάσει του
                                ΤΡΟΠΟΥ ΠΛΗΡΩΜΗΣ που εσείς θα επιλέξετε, ανεξάρτητα του ποσού που θα ανέρχεται η παραγγελία σας:
                                <ol>
                                    <li>Αν επιλέξετε να εξοφλήσετε το ποσό της προσφοράς τοις μετρητοίς,
                                    έχετε έκπτωση 5% επί του τιμολογίου της προσφοράς</li>
                                    <li>Αν επιλέξετε να εξοφλήσετε το ποσό της προσφοράς με
                                    επιταγή 60 ημερών, έχετε έκπτωση 4% επί του τιμολογίου της προσφοράς</li>
                                </ol>
                            </li>
                        </ol>
                    </textarea>  
                    <label style="margin-top:10px;">Αρχείο Excel</label>
                    <input style="border: unset; padding:0; outline: 1px solid #ccd4da;" type="file" name="file2" class="form-control"><br>
                    <label style="width: 100%;">
                        <div class="card-header d-flex justify-content-between align-items-center" style="padding-bottom: 16px; padding-top: 20px;">
                            Εμφάνιση Ποσοτήτων
                            <input type="checkbox" name="quantity2" value="quantity2">
                        </div>
                    </label>
                </div>
            </div>
            <div class="card col-sm-4 bg-light m-0 mt-3">
                <label>
                    <div class="card-header d-flex justify-content-between align-items-center">
                        Φάρμακα 
                        <input type="checkbox" name="farmaka" value="farmaka" checked="checked">
                    </div>
                </label>
                <div class="card-body">
                    <label for="title3">Τίτλος</label>
                    <input style="width: 100%; height: 35px; padding: 0 15px; margin-bottom: 15px; border: 1px solid #ddd;" type="text" name="title3" id="title3" value="ΠΡΟΣΦΟΡΑ ΦΑΡΜΑΚΟΥ">
                    <label for="subtitle3">Υπότιτλος</label>
                    <input style="width: 100%; height: 35px; padding: 0 15px; margin-bottom: 15px; border: 1px solid #ddd;" type="text" name="subtitle3" id="subtitle3" value="ΣΕΠΤΕΜΒΡΙΟΥ - ΟΚΤΩΒΡΙΟΥ 2019"> 
                    <textarea name="editor3" id="editor3" rows="10" cols="80">
                        <div style="text-align: center;">
                            <h3><strong><ins>ΠΕΡΙΕΧΟΜΕΝΑ</ins></strong></h3>
                            <br><br>
                            <h3><strong><ins>ΣΗΜΕΙΩΣΗ</ins></strong></h3><br>
                            <h3><strong>ΠΑΡΑΚΑΛΩ ΔΙΑΒΑΣΤΕ ΠΡΟΣΕΚΤΙΚΑ</strong></h3><br>
                        </div>
                        <b>Για την παρούσα προσφορά ισχύουν οι παρακάτω όροι:</b>
                        <br><br>
                        <ol>
                            <li>Το τεύχος αυτό συμπληρώνεται από εσάς και αποστέλλεται μέσω του δικτύου διανομής της αποθήκης πίσω σε μας ώστε να εκτελεστεί.</li>
                            <li>Η προσφορά εκτελείται και εξοφλείται ξεχωριστά από τις καθημερινές σας παραγγελίες.</li>
                            <li>Θα ενημερώνεστε πριν την αποστολή της προσφοράς σε εσάς για το συνολικό ποσό που αυτή ανέρχεται.</li>
                            <li>Η πληρωμή θα γίνεται με την παραλαβή της παραγγελίας.</li>
                            <li>Ελάχιστο ποσό παραγγελίας είναι τα 1000 €.</li>
                            <li>Δεν συσχετίζεται με τις υπόλοιπες προσφορές της φαρμακαποθήκης.</li>
                            <li>Μπορείτε να παραγγείλετε οποιεσδήποτε ποσότητες επιθυμείτε από κάθε προϊόν. Συμπληρώνετε την ποσότητα που επιθυμείτε στο κουτάκι δίπλα σε κάθε προϊόν.</li>
                            <li>Οι προσφορές ισχύουν κατόπιν ύπαρξης αποθέματος. Αν κάποιο από τα προϊόντα που παραγγείλατε έχει εξαντληθεί προσωρινά, θα ενημερώνεστε τηλεφωνικά από την αποθήκη μας ώστε να εξυπηρετηθείτε με τον καλύτερο δυνατό τρόπο.</li>
                            <li>Οι εκπτώσεις ακολουθούν την παρακάτω κλίμακα βάσει του
                                ΤΡΟΠΟΥ ΠΛΗΡΩΜΗΣ που εσείς θα επιλέξετε, ανεξάρτητα του ποσού που θα ανέρχεται η παραγγελία σας:
                                <ol>
                                    <li>Αν επιλέξετε να εξοφλήσετε το ποσό της προσφοράς τοις μετρητοίς,
                                    έχετε έκπτωση 5% επί του τιμολογίου της προσφοράς</li>
                                    <li>Αν επιλέξετε να εξοφλήσετε το ποσό της προσφοράς με
                                    επιταγή 60 ημερών, έχετε έκπτωση 4% επί του τιμολογίου της προσφοράς</li>
                                </ol>
                            </li>
                        </ol>
                    </textarea>                 
                    <label style="margin-top:10px;">Αρχείο Excel</label>
                    <input style="border: unset; padding:0; outline: 1px solid #ccd4da;" type="file" name="file3" class="form-control"><br>
                    <label style="width: 100%;">
                        <div class="card-header d-flex justify-content-between align-items-center" style="padding-bottom: 16px; padding-top: 20px;">
                            Εμφάνιση Ποσοτήτων
                            <input type="checkbox" name="quantity3" value="quantity3">
                        </div>
                    </label>
                </div>
            </div>
        </div>
        <br>
        <button class="btn btn-success">Import Data</button>
    </form>
</div>
@endsection

resources/views/layouts/catalogue.blade.php
@extends('pdf')
@section('catalogue')
@foreach ($row as $k => $r)

              @if ($r['kodikos'] == 'space')
              <tr class="logos"><td></td><td><div class="spacer"></div></td></tr>
              @continue
              @elseif ($r['kodikos'] == 'brand') 
              <tr class="logos"><td></td><td><span style="color: #016b5b; font-size: 30px; font-weight:bold; margin-left: -88px;">{{$r['eidos']}}</span></td>
                <td></td><td></td>
                <td>
                  <img style="position: absolute; right:0;" src="{{asset('assets/img/logo_bg.png')}}" alt="logo-bg">
                </td>
              </tr>
              @if ($row[$k+1]['kodikos'] != 'text')
              <tr>
                <td><b>Κωδικός</b></td>
                <td><b>Είδος</b></td>
                <td><b>Τεμάχια</b></td>
                <td><b>Έκπτωση</b></td>
                <td><b>Χονδρική τιμή</b></td>
                <td><b>Ποσότητα</b></td>
              </tr>
              @endif
              @continue
              @elseif ($r['kodikos'] == 'ad')
              <tr><td class="ads"><img src="{{ asset('storage/general/' . $r['eidos'])}}"></td></tr>
              @continue
              @elseif ($r['kodikos'] == 'text')
              <tr class="text"><td></td><td><span style="font-size: 15px; font-style: italic;"><b>{{$r['eidos']}}</b></span></td></tr>
              @if ($row[$k-1]['kodikos'] == 'brand')
              <tr>
                <td><b>Κωδικός</b></td>
                <td><b>Είδος</b></td>
                <td><b>Τεμάχια</b></td>
                <td><b>Έκπτωση</b></td>
                <td><b>Χονδρική τιμή</b></td>
                <td><b>Ποσότητα</b></td>
              </tr>
              @endif
              @continue
              @endif
              <tr>
                {{-- Row with children --}}
                @if (!(empty($r['kodikos'])) && empty($row[$loop->index+1]['kodikos']))
                <?php 
                $k=count($row); 
                $count=0;
                ?>
                @for ($i = 1; $i < $k-$loop->index; $i++)
                @if (empty($row[$loop->index+$i]['kodikos']))
                <?php $count++; ?>
                @else 
                @break;
                @endif
                @endfor
                @if (empty($row[$loop->index+$count]['kodikos'] && !$loop->last))
                <td rowspan="{{$count+1}}"><span>{{ $r['kodikos'] }} </span></td>
                <td rowspan="{{$count+1}}"><span>{{ $r['eidos'] }} </span></td>
                @endif
                {{-- Row without children --}}
                @elseif (!empty($r['kodikos']) && !empty($row[$loop->index+1]) && !$loop->last) 
                <td>{{ $r['kodikos'] }} </td>
                <td>{{ $r['eidos'] }} </td>
                @else
                <td style="display: none;"></td><td style="display: none;"></td>
                @endif
                <td>{{ $r['temaxia'] }} </td>
                <td>@if ($r['ekptosi'] > 0 && $r['ekptosi'] <= 1) 
                  {{$r['ekptosi']*100 }}%
                  @else 
                  {{ $r['ekptosi'] }}
                  @endif
                </td>
                <td>{{ $r['xondriki_timi'] }}@if (!empty($r['xondriki_timi']))&euro; @endif</td>
                <td>{{ $r['posotita'] }} </td>
              </tr>
              @php
              if (!empty($r['temaxia']))
                $temp1 = 1;
              if (!empty($r['ekptosi']))
                $temp2 = 1;
              if (!empty($r['xondriki_timi']))
                $temp3 = 1;
              if (!empty($r['posotita']))
                $temp4 = 1;
              @endphp
              @endforeach
@endsection

resources/views/old/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection